name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: rustup component add rustfmt
    - run: cargo fmt --all --check

  test:
    runs-on: ${{ matrix.os }}
    env:
      CARGO_PROFILE_DEV_DEBUG: 1
      CARGO_PROFILE_TEST_DEBUG: 1
      CARGO_INCREMENTAL: 0
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          rust: stable
        - os: ubuntu-latest
          rust: nightly
        - os: macos-latest
          rust: stable
        - os: windows-latest
          rust: stable-msvc
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    
    - name: Build library
      run: cargo build --verbose
    
    - name: Test library
      run: cargo test --verbose --no-fail-fast
    
    - name: Clippy
      run: cargo clippy --all-targets
